import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { COLOURS } from '../support/tokens'

/*
 * The site icon (issue #311).
 *
 * `app/icon.svg` is generated by `pnpm brand:art` and committed, so the thing
 * CI has to check is that what was committed still agrees with the palette and
 * still draws the mark the header draws. The colours are compared against
 * app/globals.css rather than a transcription — a token retuned there and not
 * regenerated here is exactly the drift this catches.
 */
const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const icon = readFileSync(join(repoRoot, 'app', 'icon.svg'), 'utf8')

/** Every colour literal in the file, lowercased. */
const used = [...icon.matchAll(/#[0-9a-fA-F]{3,8}\b/g)].map((match) => match[0].toLowerCase())

describe('app/icon.svg', () => {
  it('is a square SVG a browser can scale to any tab size', () => {
    expect(icon).toMatch(/^<svg[^>]*viewBox="0 0 64 64"/)
    expect(icon).toMatch(/<title>Docify<\/title>/)
  })

  it('draws every colour from the @theme palette', () => {
    const palette = [...COLOURS.values()]

    expect(used.length).toBeGreaterThan(0)
    expect(used.filter((colour) => !palette.includes(colour))).toEqual([])
  })

  it('is the header mark on its own ground: ink, brush, white frame, near-black letter', () => {
    // `ink` rather than the header's `shell`: a pale tile disappears into the
    // browser chrome around it, and the frame with it.
    expect(used).toContain(COLOURS.get('ink'))
    expect(used).toContain(COLOURS.get('brush'))
    expect(used).toContain(COLOURS.get('fg-dark'))
    expect(used).toContain(COLOURS.get('fg-light'))
  })

  it('sets the letter as a path, because a favicon has no webfont', () => {
    expect(icon).not.toMatch(/<text[\s>]/)
    expect(icon).toMatch(/fill-rule="evenodd"/)
  })
})
